adam_b1: 0.9
adam_b2: 0.999
in_channels: 256
mid_channels: 1024
hidden_depth: 2
n_flows: 12
n_down: 4
conditioning_in_ch: 1
conditioning_spatial_size: 128
cuda: true
data_norm: meanstd
data_subset: 1.0
devices: 0
dryrun: true
epochs: 500
imgsize: 0
loginterv: 4
lr: 1.0e-05
mbs: 128
num_workers: 4
optimizer: adam
patchsize: 128
seed: 1332
trainer: cinn