adam_b1: 0.5
adam_b2: 0.999
alpha: 0.0011852172680049085
beta: 0.12101882347522842
conditional: true
cond_critic: true
criterion: l1
cuda: true
data_norm: meanstd
data_subset: 1.0
devices:
- 0
- 1
domain: x
dryrun: true
encoder_pretrained: true
encoder_type: resnet50
encoder_norm: bn
decoder_norm: an
decoder_chn: 96
epochs: 400
greybox: wganvgg
kl_weight: 0.5750362872947617
lam: 10.0
loginterv: 4
lr: 1.0e-05
mbs: 64
num_workers: 4
optimizer: adam
imgsize: 0
patchsize: 128
seed: 1332
trainer: vae
z_dim: 256